export const AUTH_API_ROUTES = {
  SIGN_UP: "https://staging.nairaboom.ng/api/signup",
  SIGN_IN: "https://staging.nairaboom.ng/api/auth",
  VALIDATE_OTP: "https://staging.nairaboom.ng/api/validate_sms",
  RESEND_OTP: "https://staging.nairaboom.ng/api/resend_sms_otp",
  AUTO_REMEMBER: "https://staging.nairaboom.ng/api/auth_remember",
  RESET_PASSWORD: "https://staging.nairaboom.ng/api/reset_password",
  CHANGE_PASSWORD: "https://staging.nairaboom.ng/api/change_password",
  LOG_OUT: "https://staging.nairaboom.ng/api/logout",
  DEV_BASE_URL: "https://staging.nairaboom.ng",
  STAGING_BASE_URL: "http://staging.nairaboom.com.ng",
  PRODUCTION_BASE_URL: "http://staging.nairaboom.com.ng",
  // PRODUCTION_BASE_URL: "https://nairaboom.com.ng",
  PRODUCTION_X_APP_KEY: "FEIX9997eQFKBCjk9FaP95YOOk013XkKgGLVz",
};
